name: nature-serve-env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - pip
  # Core scientific python
  - numpy
  - matplotlib
  - pyqt
  - seaborn
  - tqdm
  - kiwisolver
  # Data gathering
  - usgs
  # Spatial packages
  - rasterio  
  - pysal
  - pyproj
  - rasterstats
  - geopy
  - cartopy
  - xarray
  - scipy
  - spectral
  - h5py
 
  #- geopandas
  - contextily
  - earthpy
  - folium
  - geojson
  - mapboxgl
  - geocoder

    
  # Natural language processing
  - nltk 
  - textblob

  # Jupyter Environment
  - autopep8
  - jupyterlab
  - notebook 
  # Do we need this?
  - ipython
  - jupyter_contrib_nbextensions
  - nbclean
  - pip:
    - pysptools

